dags:
  gitSync:
    repo: git@github.com:wmeints/mlops-airflow-sample.git
    branch: main
    depth: 1
    enabled: true
    subPath: src/pipelines/
    sshKeySecret: airflow-ssh-secret
    knownHosts: |-
      github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
executor: KubernetesExecutor
enablePodLaunching: true

config:
  elasticsearch:
    host: "elasticsearch-master.logging.svc.cluster.local:9200"
    write_stdout: "True"
    log_id_template: "{dag_id}_{task_id}_{execution_date}_{try_number}"

elasticsearch:
  connection: 
    host: elasticsearch-master.logging.svc.cluster.local
    port: 9200
  enabled: true