logstashConfig:
  logstash.yml: |
    http.host: 0.0.0.0
    xpack.monitoring.elasticsearch.hosts: ["http://elasticsearch-master.logging.svc.cluster.local:9200"]
    xpack.monitoring.enabled: false
logstashPipeline:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    filter {
      if [dag_id] and [task_id] and [execution_date] and [try_number] {
        mutate {
          add_field => {
            "log_id" => "%{[dag_id]}-%{[task_id]}-%{[execution_date]}-%{[try_number]}"
          }
        }
      }
    }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch-master.logging.svc.cluster.local:9200"]
        index => "filebeat-%{+YYYY.MM.dd}"
        ssl => false
        ssl_certificate_verification => false
      }
    }