daemonset:
  filebeatConfig:
    filebeat.yml: |
      filebeat.inputs:
        - type: container
          paths:
            - /var/log/containers/*.log
          processors:
            - decode_json_fields:
                fields: ["message"]
                target: ""
                overwrite_keys: true
            - add_kubernetes_metadata:
                host: ${NODE_NAME}
                matchers:
                - logs_path:
                    logs_path: "/var/log/containers/"
            - rename:
                fields:
                  - from: "log.offset"
                    to: "offset"
      processors:
        - add_cloud_metadata:

      output.logstash:
        hosts: ["logstash-logstash-headless.logging.svc.cluster.local:5044"]